# Generated by Django 5.0.6 on 2024-06-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_ordercancel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCancel',
        ),
    ]
